
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nitro V
 */
public class TransactionFrame extends javax.swing.JFrame {
    DefaultTableModel cartModel;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionFrame.class.getName());

    /**
     * Creates new form TransactionFrame
     */
    public TransactionFrame() {
        initComponents();
        
        listProducts.setListData(DataStorage.products);
        
        cartModel = (DefaultTableModel) tblCart.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnGoToInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        btnGoLogs = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQty.setBackground(new java.awt.Color(127, 123, 123));
        txtQty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtQty.setForeground(new java.awt.Color(209, 190, 190));
        txtQty.setText("1");
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 40, 40));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(209, 190, 190));
        jButton1.setText("Complete Purchase");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 150, 58));

        btnGoToInventory.setBackground(new java.awt.Color(102, 102, 102));
        btnGoToInventory.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGoToInventory.setForeground(new java.awt.Color(209, 190, 190));
        btnGoToInventory.setText("View inventory");
        btnGoToInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoToInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 130, 60));

        listProducts.setBackground(new java.awt.Color(128, 123, 123));
        listProducts.setFont(new java.awt.Font("Segoe UI Black", 2, 27)); // NOI18N
        listProducts.setForeground(new java.awt.Color(209, 190, 190));
        listProducts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listProducts);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 210));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 30));

        Quantity.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        Quantity.setForeground(new java.awt.Color(204, 204, 255));
        Quantity.setText("Quantity         Cart");
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 51, 320, 37));

        btnGoLogs.setBackground(new java.awt.Color(102, 102, 102));
        btnGoLogs.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnGoLogs.setForeground(new java.awt.Color(209, 190, 190));
        btnGoLogs.setText("Logs");
        btnGoLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLogsActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 86, 60));

        jScrollPane3.setBackground(new java.awt.Color(0, 153, 204));
        jScrollPane3.setForeground(new java.awt.Color(153, 153, 255));

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Unit Price", "Qty", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCart);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 260, 150));

        lblTotal.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(204, 204, 255));
        lblTotal.setText("Total: P0.00");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 308, 350, 36));

        btnCheckout.setBackground(new java.awt.Color(102, 102, 102));
        btnCheckout.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(209, 190, 190));
        btnCheckout.setText("CheckOut");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 48));

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(209, 190, 190));
        btnAdd.setText("Add to cart");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 105, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 40, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cf78370f-06bf-4356-a9e6-44a8ff1c7e13.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
    int itemIdx =jComboBox1.getSelectedIndex();
    int qty = Integer.parseInt(txtQty.getText());

    // Validation
    if (qty > DataStorage.stock[itemIdx]) {
        JOptionPane.showMessageDialog(this, "Insufficient Stock!");
    } else if (qty <= 0) {
        JOptionPane.showMessageDialog(this, "Invalid Quantity!");
    } else {
        // Process
        double total = qty * DataStorage.prices[itemIdx];
        DataStorage.stock[itemIdx] -= qty; // Update Inventory

        // Record Log
        DataStorage.logNames[DataStorage.logIndex] = DataStorage.products[itemIdx];
        DataStorage.logQtys[DataStorage.logIndex] = qty;
        DataStorage.logTotals[DataStorage.logIndex] = total;
        DataStorage.logIndex++;

        JOptionPane.showMessageDialog(this, "Transaction Complete!");
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Please enter a valid number.");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGoToInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToInventoryActionPerformed
    InventoryFrame inv = new InventoryFrame(); 
    
    // 2. Make the new window appear
    inv.setVisible(true); 
    
    // 3. Close (dispose) the current transaction window 
    // so you don't have 100 windows open at once.
    this.dispose(); 
    }//GEN-LAST:event_btnGoToInventoryActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    // 1. Get the index of the selected item from the JList
    int selectedIdx = listProducts.getSelectedIndex();
    
    // Check if the user actually selected something
    if (selectedIdx == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product from the list!");
        return;
    }

    try {
        // 2. Get the quantity from the text field
        int qty = Integer.parseInt(txtQty.getText());
        
        if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.");
            return;
        }

        // 3. Fetch price from DataStorage and calculate subtotal
        String productName = DataStorage.products[selectedIdx];
        double price = DataStorage.prices[selectedIdx];
        double subtotal = qty * price;

        // 4. Add the row to your cartModel (the clipboard for tblCart)
        // Order: Item Name, Unit Price, Quantity, Subtotal
        cartModel.addRow(new Object[]{productName, price, qty, subtotal});

        // 5. Update the Total Label (Optional helper method)
        updateGrandTotal();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity.");
    }
    }

    private void updateGrandTotal() {
        double grandTotal = 0;
        for (int i = 0; i < cartModel.getRowCount(); i++) {
            double rowSubtotal = (double) cartModel.getValueAt(i, 3);
            grandTotal += rowSubtotal;
        }
   

    
    // Update the label text (lblTotal is the name from Step 1)
 lblTotal.setText("Total: P" + String.format("%.2f", grandTotal));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
    
    // Loop through every row in your Cart
    for (int i = 0; i < model.getRowCount(); i++) {
        String pName = model.getValueAt(i, 0).toString();
        int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
        double subtotal = Double.parseDouble(model.getValueAt(i, 3).toString());

        // 1. Find product index in DataStorage to update stock
        for (int j = 0; j < DataStorage.products.length; j++) {
            if (DataStorage.products[j].equals(pName)) {
                DataStorage.stock[j] -= qty; 
                break;
            }
        }

        // 2. Save into Log Arrays
        DataStorage.logNames[DataStorage.logIndex] = pName;
        DataStorage.logQtys[DataStorage.logIndex] = qty;
        DataStorage.logTotals[DataStorage.logIndex] = subtotal;
        DataStorage.logIndex++;
    }

    JOptionPane.showMessageDialog(this, "Checkout Successful!");
    model.setRowCount(0); // Clear the cart table UI
    lblTotal.setText("Total: P0.00");

    
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnGoLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLogsActionPerformed
    LogsFrame logs = new LogsFrame();
    logs.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnGoLogsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnGoLogs;
    private javax.swing.JButton btnGoToInventory;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> listProducts;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
